### ISSUE TITLE
[windows] Extract Failed

### ISSUE THREAD

**Issue by evileyecc1** [electron/asar#136]
```
$ asar e app.asar ./game
C:\Users\evileyecc\AppData\Roaming\npm\node_modules\asar\node_modules\_chromium-pickle-js@0.2.0@chromium-pickle-js\lib\pickle.js:74
      throw new Error('Failed to read data with length of ' + length)
      ^

Error: Failed to read data with length of 926763878
    at PickleIterator.getReadPayloadOffsetAndAdvance (C:\Users\evileyecc\AppData\Roaming\npm\node_modules\asar\node_modules\_chromium-pickle-js@0.2.0@chromium-pickle-js\lib\pickle.js:74:13)
    at PickleIterator.readBytes (C:\Users\evileyecc\AppData\Roaming\npm\node_modules\asar\node_modules\_chromium-pickle-js@0.2.0@chromium-pickle-js\lib\pickle.js:63:34)
    at PickleIterator.readString (C:\Users\evileyecc\AppData\Roaming\npm\node_modules\asar\node_modules\_chromium-pickle-js@0.2.0@chromium-pickle-js\lib\pickle.js:59:17)
    at Object.module.exports.readArchiveHeaderSync (C:\Users\evileyecc\AppData\Roaming\npm\node_modules\asar\lib\disk.js:91:48)
    at Object.module.exports.readFilesystemSync (C:\Users\evileyecc\AppData\Roaming\npm\node_modules\asar\lib\disk.js:97:25)
    at Object.module.exports.extractAll (C:\Users\evileyecc\AppData\Roaming\npm\node_modules\asar\lib\asar.js:183:27)
    at Command.<anonymous> (C:\Users\evileyecc\AppData\Roaming\npm\node_modules\asar\bin\asar.js:60:15)
    at Command.listener (C:\Users\evileyecc\AppData\Roaming\npm\node_modules\asar\node_modules\_commander@2.11.0@commander\index.js:300:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
```
The file too big?

**Comment by coderfox** [comment]
Same question, with length `1631168572`.

**Comment by phiree** [comment]
any update for this error?

**Comment by MarshallOfSound** [comment]
Closing this old issue as it is likely fixed by now, if not please raise a new issue.
