### ISSUE TITLE
RangeError: Maximum call stack size exceeded (ASAR being created via of electron-packager)

### ISSUE THREAD

**Issue by corvinrok** [electron/asar#139]
# Summary
I am getting a blocking bug/crash during an electron-packager operation that involves ASAR packaging with an unpackDir option, which itself includes a native package.

# Environment

-  Host Operating system: win32 [Windows 7 SP1]
-  Target Architectures: x64
-  Node v8.9.4  (latest LTS) 
-  ASAR [included through a dependency of electron-packager via version  "asar": "^0.14.0"]
-  Electron Packager 10.1.1 [module to which I am making the api call]
-  Electron version: 1.8.2-beta.3 [the version of electron being packaged]

# Details
The crash is reporting as `RangeError: Maximum call stack size exceeded` and is happening whenever building (with electron-packager) where a native compiled package (in this case libxml-xsd, libxmljs-mt) is listed in the unpackDir exception property of asar option on the API call. 

Here is the pertinent setup and API call in which I see the error:
```
var opts = {
    name: pkg.name,
    platform: 'win32',
    arch: 'ia32',                           // ia32, x64 or all
    dir: config.root,                       // source location of app
    out: config.electronbuild,              // destination location for app os/native binaries
    ignore: config.electronignore,          // don't include these directories in the electron app build
    icon: config.icon,
    asar: {unpackDir: config.electroncompiled},  // compress project/modules into an asar blob
    overwrite: true,
    prune: true,
    electronVersion: electronVersion,    // Tell the packager what version of electron to build with
    appCopyright: pkg.copyright,         // copyright info
    appVersion: usableBuildVersion,      // The version of the application we are building
    win32metadata: {                     // Windows Only config data
        CompanyName: pkg.authors,
        ProductName: pkg.name,
        FileDescription: pkg.description,
        OriginalFilename: pkg.name + '.exe'
    }
};

gulp.task('build:electron', function (cb) {

    $.util.log('Launching task to build & package binaries for',
        $.util.colors.cyan(opts.name),
        $.util.colors.magenta('v' + opts.appVersion)
    );
    opts.arch = process.arch;
    packager(opts, function (err, appPath) {
        if (!err) {
            $.util.log(' <- packagerDone()', err, appPath);
            cb();
        } else {
            cb(err);
        }
    });
});
```

# Error
Calling this produces the error as follows:

```
C:\git\my-application>gulp build:electron
[11:39:48] Using gulpfile C:\git\my-application\gulpfile.js
[11:39:48] Starting 'build:electron'...
[11:39:48] Launching task to build & package binaries for MyApplication v0.2.11
  electron-packager Electron Packager 10.1.1 +0ms
  electron-packager Node v8.9.4 +1ms
  electron-packager Host Operating system: win32 (x64) +1ms
  electron-packager Packager Options: {"name":"MyApplication","platform":"win32","arch":"x64","dir":"./","out":"./edist/","ignore":[{},{},{},{},{},{},{},{},{}],"icon":"./ClientSide/app/images/icons/MyApplication.ico","asar":{"unpackDir":"node_modules{libxml-xsd,libxmljs-mt,nslog}/**/*"},"overwrite":true,"prune":true,"electronVersion":"1.8.2-beta.3","appCopyright":"Copyright (C) My Company. All Rights Reserved","appVersion":"0.2.11","win32metadata":{"CompanyName":["My Application Team"],"ProductName":"MyApplication","FileDescription":"My Application Project","OriginalFilename":"MyApplication.exe"}} +0ms
  electron-packager Target Platforms: win32 +2ms
  electron-packager Target Architectures: x64 +2ms
  electron-packager Application name: MyApplication +1ms
  electron-packager Target Electron version: 1.8.2-beta.3 +0ms
  electron-packager Ignored path regular expressions: [ /\/\.idea$/,
  /\/\b(ci|ClientSide|WiXInstaller|loaders|edist|ExternalStyles)$/,
  /\/\b(ServerSide\/test)$/,
  /(\.htmlhintrc|\.jscsrrc|\.jshintrc|.stylelintrc|tslint\.json)$/,
  /(gulp\.config\.js|gulpfile\.js)$/,
  /(karma\.conf\.js|karmaBase\.conf\.js|karmaDebug\.conf\.js)$/,
  /(webpack\.config\.js|webpack\.testConfig\.js|webpack\.UnittestConfig\.js|webpackBase\.config\.js)$/,
  /(tsconfig\.json)$/,
  /(\.gitignore|README\.md)$/,
  '/node_modules/electron($|/)',
  '/node_modules/electron-prebuilt(-compile)?($|/)',
  '/node_modules/electron-packager($|/)',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"platform":"win32","arch":"x64","version":"1.8.2-beta.3"} +0ms
Packaging app for platform win32 x64 using electron v1.8.2-beta.3
  electron-packager Creating C:\Users\joe_developer\AppData\Local\Temp\electron-packager\win32-x64-template +16s
  electron-packager Extracting C:\Users\joe_developer\.electron\electron-v1.8.2-beta.3-win32-x64.zip to C:\Users\joe_developer\AppData\Local\Temp\electron-packager\win32-x64-template +5ms
  electron-packager Initializing app in C:\Users\joe_developer\AppData\Local\Temp\electron-packager\win32-x64\MyApplication-win32-x64 from C:\Users\joe_developer\AppData\Local\Temp\electron-packager\win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ 'C:\\git\\my-application\\edist' ] +18s
  electron-packager Pruning modules via: npm prune --production +0ms
  electron-packager Running asar with the options {"unpackDir":"node_modules/{libxml-xsd,libxmljs-mt,nslog}/**/*"} +3m
C:\git\my-application\node_modules\asar\lib\disk.js:33
      return callback(error)
             ^

RangeError: Maximum call stack size exceeded
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:33:14)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)
    at writeFileListToStream (C:\git\my-application\node_modules\asar\lib\disk.js:35:12)

C:\git\my-application>
```
  
# Background
When I originally found this issue, it was reported to the issues in `electron-packager`. The maintainer (@malept ) of that package and I investigated it as seen in this issue thread [electron-packager#issue733](https://github.com/electron-userland/electron-packager/issues/733). I was able to build a sample project that is available for anyone to test and reproduce the issue (see next section). The maintainer of electron-packager believes that this issue lies within ASAR. I know from my testing that it specifically happens when the `ASAR` option `unpackDir` includes these native modules {libxml-xsd, libxmljs-mt). If I remove those native modules, the error does not happen. Something about ASAR trying to use the `unpackDir` option with those modules seems to be failing and causing the error seen above.  

**IMPORTANT**: It is important to note that this building configuration works with Node 7.10.1, but now fails with any version of Node 8.

# How to reproduce:

Using the project repo at this location:
[https://github.com/corvinrok/electron-quick-start](https://github.com/corvinrok/electron-quick-start)

You can produce the issue.

```
# Clone this repository
git clone https://github.com/corvinrok/electron-quick-start
# Go into the repository
cd electron-quick-start
# Install dependencies
npm install
# Recompile native modules with Electron bindings
gulp erebuild

# Build the native platform app
gulp build:electron
# THE ABOVE STEP FAILS
```

More details on how to do this are : 
[https://github.com/corvinrok/electron-quick-start#to-use](https://github.com/corvinrok/electron-quick-start#to-use)

**Comment by corvinrok** [comment]
Thank you!!
