### ISSUE TITLE
Cannot read property 'stack' of null

### ISSUE THREAD

**Issue by anymost** [electron/asar#151]
$ electron . NODE_ENV=devlopment
/Fine/gui/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:55
  stack = (ref = error.stack) != null ? ref : error.name + ': ' + error.message
                       ^

TypeError: Cannot read property 'stack' of null
    at process.<anonymous> (/Fine/gui/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:55:24)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:383:26)
error Command failed with exit code 7.

I run electron, then this error happened, wish to fix

**Comment by malept** [comment]
Electron itself doesn't use this module to read the asar file.
