### ISSUE TITLE
Unable to extract an archive because of a non-existent file

### ISSUE THREAD

**Issue by m4heshd** [electron/asar#182]
Hello everyone,

I'm getting this error whenever i try to unpack an asar archive with the `'node-mac-notifier'` module inside it. Tried multiple versions of asar both CLI and JS. 

```
fs.js:667
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '...\mac\app.asar.unpacked\node_modules\node-mac-notifier\.gitignore'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at Object.module.exports.readFileSync (...\node_modules\asar\lib\disk.js:121:17)
    at filenames.map (...\node_modules\asar\lib\asar.js:227:28)
    at Array.map (<anonymous>)
    at Object.module.exports.extractAll (...\node_modules\asar\lib\asar.js:205:20)
    at Object.<anonymous> (...\index.js:9:6)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
```

Can't find the issue here. ~~Pretty sure it's because of some unique characteristic of that .gitignore file.~~
Nope. Just checked. Error occurs on another file if i ignore that .gitignore file. Some weird issue this is.

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Can you provide a detailed list of repro steps to create an asar file that breaks in the way you describe?

**Comment by m4heshd** [comment]
That's why i mentioned that specific module. Lemme try to upload the asar file.

**Comment by m4heshd** [comment]
Closing this because it turned into something else.
