### ISSUE TITLE
Cannot read property 'link" of undefined

### ISSUE THREAD

**Issue by Miosame** [electron/asar#196]
Getting following error while trying to extract on Ubuntu 20.04, with both latest and lts node.

```
/home/chernika/n/lib/node_modules/asar/lib/filesystem.js:140
    if (info.link && followLinks) {
             ^

TypeError: Cannot read property 'link' of undefined
    at Filesystem.getFile (/home/chernika/n/lib/node_modules/asar/lib/filesystem.js:140:14)
    at Object.module.exports.extractFile (/home/chernika/n/lib/node_modules/asar/lib/asar.js:166:61)
    at Command.<anonymous> (/home/chernika/n/lib/node_modules/asar/bin/asar.js:65:12)
    at Command.listener [as _actionHandler] (/home/chernika/n/lib/node_modules/asar/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/home/chernika/n/lib/node_modules/asar/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/home/chernika/n/lib/node_modules/asar/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/home/chernika/n/lib/node_modules/asar/node_modules/commander/index.js:882:12)
    at Command.parse (/home/chernika/n/lib/node_modules/asar/node_modules/commander/index.js:717:10)
    at Object.<anonymous> (/home/chernika/n/lib/node_modules/asar/bin/asar.js:80:9)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
```

**Comment by Miosame** [comment]
Reinstalling node fixed it

**Comment by mckravchyk** [comment]
Same issue here. I'm using nvm.

**Comment by joelfischerr** [comment]
I ran into the same issue when using `electron-installer-debian` and fixed it by allowing copying `package.json` into the asar file.

**Comment by Edythator** [comment]
Having this issue as well, no clue how to fix it.
