### ISSUE TITLE
ERR_BUFFER_OUT_OF_BOUNDS error

### ISSUE THREAD

**Issue by dericgit** [electron/asar#204]
i use asar extract a archive,   for example ; asar e demo.asar demo,  oops error 
internal/buffer.js:75
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:75:11)
    at Buffer.readUInt32LE (internal/buffer.js:211:5)
    at Pickle.getPayloadSize (/usr/local/lib/node_modules/asar/node_modules/chromium-pickle-js/lib/pickle.js:192:24)
    at new PickleIterator (/usr/local/lib/node_modules/asar/node_modules/chromium-pickle-js/lib/pickle.js:27:28)
    at Pickle.createIterator (/usr/local/lib/node_modules/asar/node_modules/chromium-pickle-js/lib/pickle.js:144:12)
    at Object.module.exports.readArchiveHeaderSync (/usr/local/lib/node_modules/asar/lib/disk.js:68:23)
    at Object.module.exports.readFilesystemSync (/usr/local/lib/node_modules/asar/lib/disk.js:84:25)
    at Object.module.exports.extractAll (/usr/local/lib/node_modules/asar/lib/asar.js:170:27)
    at Command.<anonymous> (/usr/local/lib/node_modules/asar/bin/asar.js:72:10)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/asar/node_modules/commander/index.js:413:31) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}

**Comment by malept** [comment]
Can you (legally) provide a minimal example of an asar exhibits this behavior?

**Comment by malept** [comment]
Since the original issue reporter has not responded to the request for additional information in about two weeks, I'm going to assume that they either found the answer in another manner or decided not to pursue this issue. If I'm incorrect, they can respond with answers to the questions posed, and I'll reopen.
