### ISSUE TITLE
bug: extractAll crashing because of non-existent file

### ISSUE THREAD

**Issue by MidKnightXI** [electron/asar#247]
Hello, I'm trying to read the content of an archive but asar is crashing when I'm trying to read it

### Example

Here's a simple code in js to reproduce the crash:

```js
const asar = require("@electron/asar");
const fs = require("fs")

asar.extractAll("app.asar", "op-gg-unpacked");
const assetDir = "op-gg-unpacked/assets/react";
const assetFiles = fs.readdirSync(assetDir);

for (let fileName of assetFiles) {
    console.log(`Patching: ${fileName}`);
}
```

```json
{
  "name": "asar_test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "",
  "dependencies": {
    "@electron/asar": "^3.2.2",
    "fs": "^0.0.1-security"
  },
  "scripts": {
    "start": "node index.js"
  }
}
```

### Error

```
yarn run v1.22.17
$ node index.js
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/Users/user/asar_test/app.asar.unpacked/node_modules/gifsicle/cli.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.module.exports.readFileSync (/Users/asar_test/node_modules/asar/lib/disk.js:110:17)
    at module.exports.extractAll (/Users/asar_test/node_modules/asar/lib/asar.js:204:28)
    at file:///Users/asar_test/index.js:5:1
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/asar_test/app.asar.unpacked/node_modules/gifsicle/cli.js'
}
error Command failed with exit code 1.
```

### Archive

[link](https://temp.sh/VCVfP/app.asar.zip)

### Platform

macOS Ventura
M1 Pro
node v16.13.1

asar 3.1.0 to 3.2.2

**Comment by khanakia** [comment]
Same issue

**Comment by yesoce** [comment]
Same issue

**Comment by Kenhuey** [comment]
is it a bug? even i change the dest path ex. ".../app.asar.extract", when call ASAR.extractAll still show dest ".../app.asar.unpacked/...'
