### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by huddhudd** [electron/asar#319]
asar e data.asar app
node:internal/buffer:88
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 4. Received -1750603808
    at new NodeError (node:internal/errors:406:5)
    at boundsError (node:internal/buffer:88:9)
    at Buffer.readUInt32LE (node:internal/buffer:222:5)
    at PickleIterator.readBytes (C:\Users\Administrator\AppData\Roaming\npm\node_modules\asar\node_modules\chromium-pickle-js\lib\pickle.js:65:21)
    at PickleIterator.readUInt32 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\asar\node_modules\chromium-pickle-js\lib\pickle.js:39:17)
    at module.exports.readArchiveHeaderSync (C:\Users\Administrator\AppData\Roaming\npm\node_modules\asar\lib\disk.js:68:40)
    at module.exports.readFilesystemSync (C:\Users\Administrator\AppData\Roaming\npm\node_modules\asar\lib\disk.js:84:25)
    at module.exports.extractAll (C:\Users\Administrator\AppData\Roaming\npm\node_modules\asar\lib\asar.js:174:27)
    at Command.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\asar\bin\asar.js:72:10)
    at Command.listener [as _actionHandler] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\asar\node_modules\commander\index.js:413:31) {
  code: 'ERR_OUT_OF_RANGE'
}

Node.js v20.8.0

**Comment by erickzhao** [comment]
Hi @huddhudd, do you have a minimal repro for this bug report?

**Comment by hallee9000** [comment]
I also encounter this issue. You can try to extract figma.app to reproduce it. Seems like there's a file called `.codesign` which causes this.

<img width="1462" alt="image" src="https://github.com/user-attachments/assets/58882c81-5caf-4c6e-a1a5-3e6bcdcf81e3">

**Comment by jimhug034** [comment]
I'm having the same issue

**Comment by MarshallOfSound** [comment]
Thanks for the report. This stack trace is from the deprecated standalone asar package on a corrupt archive with no minimal repro, and current @electron/asar validates header size and throws a clear corruption error, so we are closing it. Please open a fresh issue with a minimal repro if it still occurs with current @electron/asar.
