### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by crystalfp** [electron/asar#337]
Installing the latest version of the package gives two deprecation notices:
```
PS> npm -g install @electron/asar@3.2.14
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

changed 13 packages in 846ms
```
Could you look at them? I think the 2nd one is straightforward to fix.
Thanks!

**Comment by erikian** [comment]
Hey @crystalfp! We plan to bump `glob` and other dependencies once we're able to upgrade the minimum Node.js version and release the next major version of `@electron/asar`, see https://github.com/electron/asar/pull/332#issuecomment-2435407933 for details. This is a valid issue so I'll keep it open until we get around to it, just wanted to let you know about the current status.

**Comment by cdonnellytx** [comment]
FYI, you cannot apply a [package.json override](https://docs.npmjs.com/cli/v10/configuring-npm/package-json?v=true#overrides) of glob to v9 or later, as `glob` now returns a Promise and the `promisify` wrapper fails when invoked.

Just posting this in case anyone makes the same mistake I did :)

```
(node:15148) [DEP0174] DeprecationWarning: Calling promisify on a function that returns a Promise is likely a mistake.
    at node:internal/util:456:17
    at new Promise (<anonymous>)
    at glob_ (node:internal/util:441:12)
    at crawl (C:\redacted\node_modules\@electron\asar\src\crawlfs.ts:34:25)
    at createPackageWithOptions (C:\redacted\node_modules\@electron\asar\src\asar.ts:56:54)
```
