### ISSUE TITLE
RangeError [ERR_INVALID_ARG_VALUE] when unpacking app.asar

### ISSUE THREAD

**Issue by TaxMachine** [electron/asar#345]
```
/home/taxmachine/squashfs-root/resources/node_modules/@electron/asar/lib/asar.js:253
        throw new Error('Unable to extract some files:\n\n' +
        ^

Error: Unable to extract some files:

RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid. Received 6.62534095087035e+306
    at Function.alloc (node:buffer:405:3)
    at Object.readFileSync (/home/taxmachine/squashfs-root/resources/node_modules/@electron/asar/lib/disk.js:129:25)
    at Object.extractAll (/home/taxmachine/squashfs-root/resources/node_modules/@electron/asar/lib/asar.js:241:38)
    at Command.<anonymous> (/home/taxmachine/squashfs-root/resources/node_modules/@electron/asar/bin/asar.js:70:10)
    at Command.listener [as _actionHandler] (/home/taxmachine/squashfs-root/resources/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/home/taxmachine/squashfs-root/resources/node_modules/commander/index.js:914:14)
    at Command._dispatchSubcommand (/home/taxmachine/squashfs-root/resources/node_modules/commander/index.js:865:18)
    at Command._parseCommand (/home/taxmachine/squashfs-root/resources/node_modules/commander/index.js:882:12)
    at Command.parse (/home/taxmachine/squashfs-root/resources/node_modules/commander/index.js:717:10)
    at Object.<anonymous> (/home/taxmachine/squashfs-root/resources/node_modules/@electron/asar/bin/asar.js:78:9)
```

I used other tools to try and unpack it and no one works, i have no idea why it does that

**Comment by MarshallOfSound** [comment]
Thanks for the report. This looks like the same corrupt/non-conforming-archive class as #319 with no minimal repro, so we are consolidating it and closing in favor of #319. Please add a minimal repro to #319 if it still occurs on a current version.
