### ISSUE TITLE
Invalid package name.asar at invalidArchiveError

### ISSUE THREAD

**Issue by PokemonAshLovesMyTurkeyAndILikeYouTwo** [electron/asar#60]
Hey team,

I'm getting this error when trying to use the asar pragmatically

```
[Error: Invalid package name.asar at invalidArchiveError (ATOM_SHELL_ASAR.js:138:13) at Objec…]
0: Error: Invalid package name.asar at invalidArchiveError (ATOM_SHELL_ASAR.js:138:13) at Object.module.(anonymous function) [as open] (ATOM_SHELL_ASAR.js:193:16) at WriteStream.open (fs.js:1927:6) at new WriteStream (fs.js:1917:10) at Object.fs.createWriteStream (fs.js:1873:10) at Object.module.exports.writeFilesystem (C:\WT-NMP\WWW\node_modules\asar\lib\disk.js:69:14) at C:\WT-NMP\WWW\node_modules\asar\lib\asar.js:120:21 at C:\WT-NMP\WWW\node_modules\asar\node_modules\mkdirp\index.js:48:26 at FSReqWrap.oncomplete (fs.js:82:15)
message: "Invalid package name.asar"
```

code:

```
 var asar = require('asar');
                                                                                        var src = './muffin';
                                                                                        var dest = 'name.asar';

                                                                                        asar.createPackage(src, dest, function() {
                                                                                          console.log('Finished Packing into file');
                                                                                          console.log(arguments);


                                                                                        });
```

**Comment by scottwey** [comment]
I think the issue might have to do with Electron's changes to `fs`.
I've received the same error. I forked asar to use `original-fs` (which is a module in Electron to expose the original `fs` functions). This has fixed the issue for me.
You can give my fork a try with the `original-fs-asar` npm package.

```javascript
var asar = require('original-fs-asar');
```

see the fork at https://github.com/scottwey/asar

**Comment by MarshallOfSound** [comment]
Using the `asar` module from within Electron is now tested and part of the `@electron/asar` test suite, this shouldn't be an issue anymore
